// A curated set of common native (Unicode) emoji for the composer's ":" picker.
// Shortcodes follow the de-facto GitHub/Slack names; `k` are extra search
// keywords. Deliberately not exhaustive (樸) - the everyday few hundred, easy to
// grow. No deps: this is just data.

export interface Emoji { char: string; name: string; k?: string[] }

export const EMOJI: Emoji[] = [
    // faces
    { char: '😀', name: 'grinning' },
    { char: '😃', name: 'smiley' },
    { char: '😄', name: 'smile' },
    { char: '😁', name: 'grin' },
    { char: '😆', name: 'laughing', k: ['satisfied'] },
    { char: '😅', name: 'sweat_smile' },
    { char: '🤣', name: 'rofl', k: ['rolling', 'laugh'] },
    { char: '😂', name: 'joy', k: ['laugh', 'lol', 'tears', 'cry'] },
    { char: '🙂', name: 'slight_smile' },
    { char: '🙃', name: 'upside_down' },
    { char: '😉', name: 'wink' },
    { char: '😊', name: 'blush' },
    { char: '😇', name: 'innocent' },
    { char: '🥰', name: 'smiling_face_with_hearts', k: ['love'] },
    { char: '😍', name: 'heart_eyes', k: ['love'] },
    { char: '🤩', name: 'star_struck' },
    { char: '😘', name: 'kissing_heart', k: ['kiss'] },
    { char: '😗', name: 'kissing' },
    { char: '😚', name: 'kissing_closed_eyes' },
    { char: '😋', name: 'yum', k: ['tasty'] },
    { char: '😛', name: 'stuck_out_tongue' },
    { char: '😜', name: 'stuck_out_tongue_winking_eye' },
    { char: '🤪', name: 'zany', k: ['crazy'] },
    { char: '😝', name: 'stuck_out_tongue_closed_eyes' },
    { char: '🤑', name: 'money_mouth' },
    { char: '🤗', name: 'hugs' },
    { char: '🤭', name: 'hand_over_mouth' },
    { char: '🤫', name: 'shushing' },
    { char: '🤔', name: 'thinking' },
    { char: '🤐', name: 'zipper_mouth' },
    { char: '🤨', name: 'raised_eyebrow' },
    { char: '😐', name: 'neutral_face' },
    { char: '😑', name: 'expressionless' },
    { char: '😶', name: 'no_mouth' },
    { char: '😏', name: 'smirk' },
    { char: '😒', name: 'unamused' },
    { char: '🙄', name: 'roll_eyes' },
    { char: '😬', name: 'grimacing' },
    { char: '🤥', name: 'lying_face' },
    { char: '😌', name: 'relieved' },
    { char: '😔', name: 'pensive' },
    { char: '😪', name: 'sleepy' },
    { char: '🤤', name: 'drooling' },
    { char: '😴', name: 'sleeping', k: ['zzz'] },
    { char: '😷', name: 'mask' },
    { char: '🤒', name: 'face_with_thermometer', k: ['sick'] },
    { char: '🤕', name: 'head_bandage' },
    { char: '🤢', name: 'nauseated' },
    { char: '🤮', name: 'vomiting' },
    { char: '🤧', name: 'sneezing' },
    { char: '🥵', name: 'hot_face' },
    { char: '🥶', name: 'cold_face' },
    { char: '🥴', name: 'woozy' },
    { char: '😵', name: 'dizzy_face' },
    { char: '🤯', name: 'exploding_head', k: ['mind', 'blown'] },
    { char: '🤠', name: 'cowboy' },
    { char: '🥳', name: 'partying_face', k: ['party'] },
    { char: '😎', name: 'sunglasses', k: ['cool'] },
    { char: '🤓', name: 'nerd' },
    { char: '🧐', name: 'monocle' },
    { char: '😕', name: 'confused' },
    { char: '😟', name: 'worried' },
    { char: '🙁', name: 'slightly_frowning' },
    { char: '😮', name: 'open_mouth' },
    { char: '😯', name: 'hushed' },
    { char: '😲', name: 'astonished' },
    { char: '😳', name: 'flushed' },
    { char: '🥺', name: 'pleading', k: ['begging', 'puppy'] },
    { char: '😨', name: 'fearful' },
    { char: '😰', name: 'cold_sweat' },
    { char: '😥', name: 'disappointed_relieved' },
    { char: '😢', name: 'cry', k: ['sad', 'tear'] },
    { char: '😭', name: 'sob', k: ['crying', 'bawling'] },
    { char: '😱', name: 'scream' },
    { char: '😖', name: 'confounded' },
    { char: '😞', name: 'disappointed' },
    { char: '😓', name: 'sweat' },
    { char: '😩', name: 'weary' },
    { char: '😫', name: 'tired_face' },
    { char: '🥱', name: 'yawning' },
    { char: '😤', name: 'triumph', k: ['huff'] },
    { char: '😡', name: 'rage', k: ['angry', 'mad'] },
    { char: '😠', name: 'angry' },
    { char: '🤬', name: 'cursing' },
    { char: '😈', name: 'smiling_imp', k: ['devil'] },
    { char: '💀', name: 'skull', k: ['dead'] },
    { char: '💩', name: 'poop', k: ['shit'] },
    { char: '🤡', name: 'clown' },
    { char: '👻', name: 'ghost' },
    { char: '👽', name: 'alien' },
    { char: '🤖', name: 'robot' },
    { char: '🎃', name: 'jack_o_lantern', k: ['pumpkin'] },
    // hands & people
    { char: '👋', name: 'wave' },
    { char: '🤚', name: 'raised_back_of_hand' },
    { char: '✋', name: 'raised_hand' },
    { char: '🖖', name: 'vulcan' },
    { char: '👌', name: 'ok_hand' },
    { char: '🤌', name: 'pinched_fingers' },
    { char: '🤏', name: 'pinching_hand' },
    { char: '✌️', name: 'v', k: ['peace', 'victory'] },
    { char: '🤞', name: 'crossed_fingers' },
    { char: '🤟', name: 'love_you_gesture' },
    { char: '🤘', name: 'metal', k: ['rock'] },
    { char: '🤙', name: 'call_me_hand', k: ['shaka'] },
    { char: '👈', name: 'point_left' },
    { char: '👉', name: 'point_right' },
    { char: '👆', name: 'point_up' },
    { char: '👇', name: 'point_down' },
    { char: '👍', name: '+1', k: ['thumbsup', 'like', 'yes'] },
    { char: '👎', name: '-1', k: ['thumbsdown', 'no'] },
    { char: '✊', name: 'fist' },
    { char: '👊', name: 'punch', k: ['fist'] },
    { char: '🤛', name: 'fist_left' },
    { char: '🤜', name: 'fist_right' },
    { char: '👏', name: 'clap' },
    { char: '🙌', name: 'raised_hands' },
    { char: '👐', name: 'open_hands' },
    { char: '🤲', name: 'palms_up' },
    { char: '🤝', name: 'handshake' },
    { char: '🙏', name: 'pray', k: ['thanks', 'please', 'hope'] },
    { char: '✍️', name: 'writing_hand' },
    { char: '💪', name: 'muscle', k: ['flex', 'strong'] },
    { char: '🫂', name: 'people_hugging', k: ['hug'] },
    { char: '👀', name: 'eyes', k: ['look', 'watch'] },
    { char: '🧠', name: 'brain' },
    { char: '👑', name: 'crown', k: ['king', 'queen'] },
    // hearts & symbols
    { char: '❤️', name: 'heart', k: ['love', 'red'] },
    { char: '🧡', name: 'orange_heart' },
    { char: '💛', name: 'yellow_heart' },
    { char: '💚', name: 'green_heart' },
    { char: '💙', name: 'blue_heart' },
    { char: '💜', name: 'purple_heart' },
    { char: '🖤', name: 'black_heart' },
    { char: '🤍', name: 'white_heart' },
    { char: '🤎', name: 'brown_heart' },
    { char: '💔', name: 'broken_heart' },
    { char: '💕', name: 'two_hearts' },
    { char: '💞', name: 'revolving_hearts' },
    { char: '💓', name: 'heartbeat' },
    { char: '💗', name: 'heartpulse' },
    { char: '💖', name: 'sparkling_heart' },
    { char: '💘', name: 'cupid' },
    { char: '💝', name: 'gift_heart' },
    { char: '💯', name: '100', k: ['hundred', 'perfect'] },
    { char: '💢', name: 'anger' },
    { char: '💥', name: 'boom', k: ['explosion', 'collision'] },
    { char: '💫', name: 'dizzy' },
    { char: '💦', name: 'sweat_drops' },
    { char: '💨', name: 'dash' },
    { char: '💬', name: 'speech_balloon' },
    { char: '💭', name: 'thought_balloon' },
    { char: '💤', name: 'zzz', k: ['sleep'] },
    { char: '🔥', name: 'fire', k: ['lit', 'hot', 'flame'] },
    { char: '⭐', name: 'star' },
    { char: '🌟', name: 'star2', k: ['glowing'] },
    { char: '✨', name: 'sparkles' },
    { char: '⚡', name: 'zap', k: ['lightning', 'bolt'] },
    { char: '☀️', name: 'sunny', k: ['sun'] },
    { char: '🌈', name: 'rainbow' },
    { char: '☁️', name: 'cloud' },
    { char: '❄️', name: 'snowflake' },
    { char: '🌊', name: 'ocean', k: ['wave', 'water'] },
    { char: '💧', name: 'droplet' },
    { char: '🌙', name: 'crescent_moon', k: ['moon'] },
    { char: '🌍', name: 'earth_africa', k: ['world', 'globe'] },
    // animals & nature
    { char: '🐶', name: 'dog' },
    { char: '🐱', name: 'cat' },
    { char: '🦊', name: 'fox' },
    { char: '🐻', name: 'bear' },
    { char: '🐼', name: 'panda' },
    { char: '🐨', name: 'koala' },
    { char: '🐯', name: 'tiger' },
    { char: '🦁', name: 'lion' },
    { char: '🐷', name: 'pig' },
    { char: '🐸', name: 'frog' },
    { char: '🐵', name: 'monkey_face' },
    { char: '🐔', name: 'chicken' },
    { char: '🐧', name: 'penguin' },
    { char: '🐦', name: 'bird' },
    { char: '🦅', name: 'eagle' },
    { char: '🦉', name: 'owl' },
    { char: '🐺', name: 'wolf' },
    { char: '🐴', name: 'horse' },
    { char: '🦄', name: 'unicorn' },
    { char: '🐝', name: 'bee' },
    { char: '🦋', name: 'butterfly' },
    { char: '🐢', name: 'turtle' },
    { char: '🐍', name: 'snake' },
    { char: '🐙', name: 'octopus' },
    { char: '🐳', name: 'whale' },
    { char: '🐬', name: 'dolphin' },
    { char: '🐟', name: 'fish' },
    { char: '🦈', name: 'shark' },
    { char: '🐘', name: 'elephant' },
    { char: '🌵', name: 'cactus' },
    { char: '🌲', name: 'evergreen_tree', k: ['tree'] },
    { char: '🌴', name: 'palm_tree' },
    { char: '🌱', name: 'seedling' },
    { char: '🍀', name: 'four_leaf_clover', k: ['luck'] },
    { char: '🍁', name: 'maple_leaf' },
    { char: '🌸', name: 'cherry_blossom' },
    { char: '🌹', name: 'rose' },
    { char: '🌻', name: 'sunflower' },
    { char: '💐', name: 'bouquet', k: ['flowers'] },
    { char: '🍄', name: 'mushroom' },
    // food & drink
    { char: '🍎', name: 'apple' },
    { char: '🍊', name: 'tangerine', k: ['orange'] },
    { char: '🍋', name: 'lemon' },
    { char: '🍌', name: 'banana' },
    { char: '🍉', name: 'watermelon' },
    { char: '🍇', name: 'grapes' },
    { char: '🍓', name: 'strawberry' },
    { char: '🍒', name: 'cherries' },
    { char: '🍑', name: 'peach' },
    { char: '🥭', name: 'mango' },
    { char: '🍍', name: 'pineapple' },
    { char: '🥥', name: 'coconut' },
    { char: '🍅', name: 'tomato' },
    { char: '🥑', name: 'avocado' },
    { char: '🌽', name: 'corn' },
    { char: '🌶️', name: 'hot_pepper', k: ['spicy'] },
    { char: '🥦', name: 'broccoli' },
    { char: '🍞', name: 'bread' },
    { char: '🧀', name: 'cheese' },
    { char: '🥚', name: 'egg' },
    { char: '🍔', name: 'hamburger', k: ['burger'] },
    { char: '🍟', name: 'fries' },
    { char: '🍕', name: 'pizza' },
    { char: '🌭', name: 'hotdog' },
    { char: '🥪', name: 'sandwich' },
    { char: '🌮', name: 'taco' },
    { char: '🌯', name: 'burrito' },
    { char: '🥗', name: 'salad' },
    { char: '🍣', name: 'sushi' },
    { char: '🍦', name: 'icecream' },
    { char: '🍩', name: 'doughnut', k: ['donut'] },
    { char: '🍪', name: 'cookie' },
    { char: '🎂', name: 'birthday', k: ['cake'] },
    { char: '🍰', name: 'cake' },
    { char: '🍫', name: 'chocolate' },
    { char: '🍬', name: 'candy' },
    { char: '🍭', name: 'lollipop' },
    { char: '🍿', name: 'popcorn' },
    { char: '☕', name: 'coffee' },
    { char: '🍵', name: 'tea' },
    { char: '🍺', name: 'beer' },
    { char: '🍻', name: 'beers' },
    { char: '🍷', name: 'wine_glass', k: ['wine'] },
    { char: '🥂', name: 'champagne', k: ['cheers', 'clink'] },
    { char: '🍸', name: 'cocktail' },
    { char: '🥃', name: 'whiskey' },
    // activities & objects
    { char: '⚽', name: 'soccer' },
    { char: '🏀', name: 'basketball' },
    { char: '🏈', name: 'football' },
    { char: '⚾', name: 'baseball' },
    { char: '🎾', name: 'tennis' },
    { char: '🎱', name: '8ball' },
    { char: '🎯', name: 'dart', k: ['target', 'bullseye'] },
    { char: '🎮', name: 'video_game', k: ['gaming'] },
    { char: '🎲', name: 'game_die', k: ['dice'] },
    { char: '🎸', name: 'guitar' },
    { char: '🎹', name: 'musical_keyboard', k: ['piano'] },
    { char: '🎺', name: 'trumpet' },
    { char: '🎻', name: 'violin' },
    { char: '🥁', name: 'drum' },
    { char: '🎤', name: 'microphone', k: ['mic'] },
    { char: '🎧', name: 'headphones' },
    { char: '🎵', name: 'musical_note', k: ['music'] },
    { char: '🎶', name: 'notes', k: ['music'] },
    { char: '🎬', name: 'clapper', k: ['movie'] },
    { char: '🎨', name: 'art', k: ['palette', 'paint'] },
    { char: '🎉', name: 'tada', k: ['party', 'celebrate', 'hooray'] },
    { char: '🎊', name: 'confetti_ball' },
    { char: '🎈', name: 'balloon' },
    { char: '🎁', name: 'gift', k: ['present'] },
    { char: '🏆', name: 'trophy', k: ['win'] },
    { char: '🥇', name: 'first_place', k: ['gold', 'medal'] },
    { char: '🚗', name: 'car' },
    { char: '✈️', name: 'airplane', k: ['flight', 'travel'] },
    { char: '🚀', name: 'rocket', k: ['launch', 'ship', 'moon'] },
    { char: '🛸', name: 'ufo' },
    { char: '⛵', name: 'sailboat' },
    { char: '🚢', name: 'ship' },
    { char: '🏠', name: 'house', k: ['home'] },
    { char: '🏔️', name: 'mountain', k: ['snow'] },
    { char: '🌋', name: 'volcano' },
    { char: '🏖️', name: 'beach', k: ['vacation'] },
    { char: '⌚', name: 'watch' },
    { char: '📱', name: 'iphone', k: ['phone', 'mobile'] },
    { char: '💻', name: 'computer', k: ['laptop'] },
    { char: '⌨️', name: 'keyboard' },
    { char: '🖥️', name: 'desktop_computer' },
    { char: '🖨️', name: 'printer' },
    { char: '💾', name: 'floppy_disk', k: ['save'] },
    { char: '📷', name: 'camera' },
    { char: '🎥', name: 'movie_camera' },
    { char: '📺', name: 'tv' },
    { char: '📻', name: 'radio' },
    { char: '🔋', name: 'battery' },
    { char: '💡', name: 'bulb', k: ['idea', 'light'] },
    { char: '🔦', name: 'flashlight' },
    { char: '🕯️', name: 'candle' },
    { char: '📡', name: 'satellite' },
    { char: '🔭', name: 'telescope' },
    { char: '🔬', name: 'microscope' },
    { char: '💰', name: 'moneybag', k: ['money'] },
    { char: '💵', name: 'dollar', k: ['money', 'cash'] },
    { char: '💳', name: 'credit_card' },
    { char: '💎', name: 'gem', k: ['diamond'] },
    { char: '🔧', name: 'wrench' },
    { char: '🔨', name: 'hammer' },
    { char: '🛠️', name: 'tools' },
    { char: '⚙️', name: 'gear', k: ['settings', 'cog'] },
    { char: '🔒', name: 'lock' },
    { char: '🔓', name: 'unlock' },
    { char: '🔑', name: 'key' },
    { char: '🧨', name: 'firecracker' },
    { char: '💣', name: 'bomb' },
    { char: '🔮', name: 'crystal_ball' },
    { char: '🧪', name: 'test_tube' },
    { char: '🧬', name: 'dna' },
    { char: '🧹', name: 'broom' },
    { char: '🛒', name: 'shopping_cart' },
    { char: '📈', name: 'chart_increasing', k: ['up', 'graph', 'gains'] },
    { char: '📉', name: 'chart_decreasing', k: ['down', 'graph', 'loss'] },
    { char: '📌', name: 'pushpin', k: ['pin'] },
    { char: '📎', name: 'paperclip' },
    { char: '📝', name: 'memo', k: ['note', 'write'] },
    { char: '📚', name: 'books' },
    { char: '📖', name: 'book' },
    { char: '✏️', name: 'pencil' },
    { char: '🖊️', name: 'pen' },
    { char: '📅', name: 'calendar' },
    { char: '⏰', name: 'alarm_clock' },
    { char: '⏳', name: 'hourglass', k: ['time', 'wait'] },
    { char: '🔔', name: 'bell' },
    { char: '📢', name: 'loudspeaker', k: ['announce'] },
    { char: '🎓', name: 'mortar_board', k: ['graduation'] },
    // symbols
    { char: '✅', name: 'white_check_mark', k: ['check', 'done', 'yes'] },
    { char: '✔️', name: 'heavy_check_mark', k: ['check'] },
    { char: '❌', name: 'x', k: ['no', 'cross', 'wrong'] },
    { char: '➕', name: 'plus' },
    { char: '➖', name: 'minus' },
    { char: '❓', name: 'question' },
    { char: '❗', name: 'exclamation' },
    { char: '⚠️', name: 'warning', k: ['caution'] },
    { char: '🚫', name: 'no_entry_sign', k: ['ban', 'forbidden'] },
    { char: '♻️', name: 'recycle' },
    { char: '🔝', name: 'top' },
    { char: '▶️', name: 'play' },
    { char: '⏸️', name: 'pause' },
    { char: '🔁', name: 'repeat' },
    { char: '🔄', name: 'arrows_counterclockwise', k: ['refresh'] },
    { char: '➡️', name: 'arrow_right' },
    { char: '⬅️', name: 'arrow_left' },
    { char: '⬆️', name: 'arrow_up' },
    { char: '⬇️', name: 'arrow_down' },
    { char: '🔴', name: 'red_circle' },
    { char: '🟠', name: 'orange_circle', k: ['bitcoin'] },
    { char: '🟡', name: 'yellow_circle' },
    { char: '🟢', name: 'green_circle' },
    { char: '🔵', name: 'blue_circle' },
    { char: '🟣', name: 'purple_circle' },
    { char: '⚫', name: 'black_circle' },
    { char: '⚪', name: 'white_circle' },
];

/** Find emoji matching a shortcode query (no leading colon). Ranked: exact name,
 * name prefix, keyword, then substring. Returns up to `limit`. */
export function searchEmoji(query: string, limit = 8): Emoji[] {
    const q = query.toLowerCase();
    if (!q) return [];
    const scored: { e: Emoji; score: number }[] = [];
    for (const e of EMOJI) {
        let score = -1;
        if (e.name === q) score = 0;
        else if (e.name.startsWith(q)) score = 1;
        else if (e.k?.some((w) => w === q)) score = 2;
        else if (e.k?.some((w) => w.startsWith(q))) score = 3;
        else if (e.name.includes(q)) score = 4;
        else if (e.k?.some((w) => w.includes(q))) score = 5;
        if (score >= 0) scored.push({ e, score });
    }
    scored.sort((a, b) => a.score - b.score);
    return scored.slice(0, limit).map((s) => s.e);
}
